[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "acallable"
version = "0.0.2"
authors = [
  { name="Alan Justino", email="alan.justino@yahoo.com.br" },
]
description = "Allows the sync function (`__call__`) to have an async version (`__acall__`)selected automatically"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]

[project.optional-dependencies]
tests = [
    "pytest>=8",
    "pytest-asyncio>=0.23",
]
dev = ["acallable[tests]", "ruff>=0.6"]

[project.urls]
Homepage = "https://github.com/alanjds/acallable"
Issues = "https://github.com/alanjds/acallable/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["acallable*"]

[tool.bumpversion]
current_version = "0.0.2"
commit = true
tag = true
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "acallable/__init__.py"

[tool.ruff]
line-length = 120
lint.extend-select = [
    # E and F are enabled by default
    'B',      # flake8-bugbear
    'C4',     # flake8-comprehensions
    'C90',    # mccabe
    'I',      # isort
    'N',      # pep8-naming
    'Q',      # flake8-quotes
    'RUF100', # ruff (unused noqa)
    'S',      # flake8-bandit
    'W',      # pycodestyle
]
lint.extend-ignore = [
    'S101', # assert is fine
    'B018', # useless expr. are useful on tests
    'N805', # some self_ are needed to mess not with real self
    'E731', # tests do assign lambdas
    'N807', # Function name __acall__ starts with `__`!
]
lint.flake8-quotes = { inline-quotes = 'single', multiline-quotes = 'double' }
lint.mccabe = { max-complexity = 25 }

[tool.ruff.format]
quote-style = 'single'

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ['acallable', 'tests']

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_mode = "auto"
addopts = ["-v", "-s", "-rxXs", "--continue-on-collection-errors"]

[tool.ty.rules]
invalid-await = "warn"  # or "ignore"

[tool.pyright]
reportGeneralTypeIssues = "warning"  # or "none"
